# METAINFORMANT Amalgkit Configuration
# Species: Temnothorax curvispinosus
# NCBI Taxonomy ID: 300111
# Assembly: GCA_014633215.1 (ilTemCurv1.2)
# Assembly Level: Chromosome
# Sequencing: PacBio + Hi-C
# Notes: Darwin Tree of Life project
# RNA-seq Samples Available: 116
# Generated: 2025-11-03


work_dir: /home/q/Documents/GitHub/MetaInformAnt/output/amalgkit/temnothorax_curvispinosus/work
log_dir: /home/q/Documents/GitHub/MetaInformAnt/output/amalgkit/temnothorax_curvispinosus/logs
threads: 24


auto_install_amalgkit: true


# Pre-selection filtering rules
filters:
  require_tissue: false  # Set to true to filter by tissue metadata


# Species configuration
species_list:
  - Temnothorax_curvispinosus


# Alternative taxonomy specification
taxon_id: 300111


# Reference genome configuration
# Based on NCBI assembly: GCA_014633215.1
genome:
  accession: GCA_014633215.1
  assembly_name: ilTemCurv1.2
  dest_dir: output/amalgkit/temnothorax_curvispinosus/genome


  # Files to download (based on available NCBI FTP resources)
  include:
    - genome           # Genomic sequences (FASTA)
    - gff3            # Gene annotations (GFF3)
    - rna             # RNA sequences (FASTA)
    - cds             # CDS sequences (FASTA)
    - protein         # Protein sequences (FASTA)
    - seq-report      # Sequence report
    - feature-table   # Feature table
    - gene-ontology   # Gene Ontology annotations (if available)


  # Direct FTP URL for all genome files
  ftp_url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/014/633/215/GCA_014633215.1_ilTemCurv1.2/


  # Specific important files for transcriptome analysis
  files:
    genomic_fasta: GCA_014633215.1_ilTemCurv1.2_genomic.fna.gz
    transcriptome_fasta: GCA_014633215.1_ilTemCurv1.2_rna_from_genomic.fna.gz
    cds_fasta: GCA_014633215.1_ilTemCurv1.2_cds_from_genomic.fna.gz
    protein_fasta: GCA_014633215.1_ilTemCurv1.2_protein.faa.gz
    annotation_gff: GCA_014633215.1_ilTemCurv1.2_genomic.gff.gz
    annotation_gtf: GCA_014633215.1_ilTemCurv1.2_genomic.gtf.gz


# Per-step parameters (merged on top of common params)
steps:
  metadata:
    # Required by amalgkit metadata
    out_dir: output/amalgkit/temnothorax_curvispinosus/work
    # Uses NCBI_EMAIL from environment; override here if needed
    # entrez_email: you@example.com
    search_string: '"Temnothorax curvispinosus"[Organism] AND RNA-Seq[Strategy] AND Illumina[Platform]'
    redo: yes
  integrate:
    fastq_dir: output/amalgkit/temnothorax_curvispinosus/fastq
  config: {}
  select: {}
  getfastq:
    out_dir: output/amalgkit/temnothorax_curvispinosus/fastq
    threads: 24
    # Cloud acceleration via individual mirrors
    aws: yes
    gcp: yes
    ncbi: yes
    pfd: no           # DISABLED: parallel-fastq-dump usually not needed
    fastp: yes        # ENABLED: fastp QC tool
  quant:
    # If a Salmon/Kallisto index is available, set it; otherwise genome_dir is injected from genome step
    out_dir: output/amalgkit/temnothorax_curvispinosus/quant
    threads: 24
    redo: no
    # Delete SRA/FASTQ files after quantification to save space
    keep_fastq: no
    # Build kallisto index if not present
    build_index: yes
  merge:
    out: output/amalgkit/temnothorax_curvispinosus/merged/merged_abundance.tsv
    out_dir: output/amalgkit/temnothorax_curvispinosus/merged
  cstmm:
    out_dir: output/amalgkit/temnothorax_curvispinosus/cstmm
  curate:
    out_dir: output/amalgkit/temnothorax_curvispinosus/curate
  csca:
    out_dir: output/amalgkit/temnothorax_curvispinosus/csca
  sanity: {}
